### ISSUE TITLE
List of operations

### ISSUE THREAD

**Issue by ITNoesis** [CommvaultEngg/ansible#1]
Need to get a list of operations which can be performed with this module apart from the ones mentioned in the readme file (backup, wait_for_completion, restore_in_place, update_subclient_description).

**Comment by Vairavaprakash** [comment]
Hi ITNoesis,

Ansible uses CVPySDK to perform operations

CVPySDK is available on GitHub -- https://github.com/CommvaultEngg/cvpysdk

Below are the modules supported by Ansible commvault module, please refer to the documentation of each module to know the list of operations supported

1. Commcell -- https://commvaultengg.github.io/cvpysdk/source/cvpysdk.html#module-cvpysdk.commcell
2. Client -- https://commvaultengg.github.io/cvpysdk/source/cvpysdk.html#module-cvpysdk.client
3. Clientgroup -- https://commvaultengg.github.io/cvpysdk/source/cvpysdk.html#module-cvpysdk.clientgroup
4. Agent -- https://commvaultengg.github.io/cvpysdk/source/cvpysdk.html#module-cvpysdk.agent
5. Instance -- https://commvaultengg.github.io/cvpysdk/source/cvpysdk.html#module-cvpysdk.instance
6. Backupset -- https://commvaultengg.github.io/cvpysdk/source/cvpysdk.html#module-cvpysdk.backupset
7. Subclient -- https://commvaultengg.github.io/cvpysdk/source/cvpysdk.html#module-cvpysdk.subclient
8. Job -- https://commvaultengg.github.io/cvpysdk/source/cvpysdk.html#module-cvpysdk.job
