### ISSUE TITLE
Ansible Galaxy

### ISSUE THREAD

**Issue by greenseeker** [CommvaultEngg/ansible#13]
Could this be published on galaxy.ansible.com so it could be installed and managed with `ansible-galaxy` like other collections?

**Comment by smatterchew** [comment]
Great idea.  This would allow us to consume the module(s) using standard processes.

**Comment by wjcbsr** [comment]
Please, please, please add to galaxy

**Comment by spakhare** [comment]
We are working on new simplified ansible collections and eventually, that would be published in the ansible galaxy. 

https://github.com/Commvault/ansiblev2
