### ISSUE TITLE
creating new servergroup (clientgroup) fails...

### ISSUE THREAD

**Issue by ndjilinski** [CommvaultEngg/ansible#6]
Hi,

From my understnding, if we want to create new clientgroup, we need still pass object_type as "clientgroup", object_operation "add" and pass new clientgroup_name in the args dict. it still want the clientgroup defined in the entity dict (to create objects for clientgroup and clientgroups). 

Workaround is to provide existing server group name, so, the python doesn't return the exception for clientgroup.get(name) API call.

or, am I missing something?

Regards,
ND

**Comment by Vairavaprakash** [comment]
Hi ND,

Thanks for letting us know, this issue has been addressed.

Please try with the latest code changes.

Regards,
VP

**Comment by ndjilinski** [comment]
Hi VP,

still, throws an error...

from my understanding, the method we create a new clientgroup is:

  commvault:
    operation: "add"
    entity_type: "clientgroup"
    commcell: "{{ commcell }}"
    args: {
          clientgroup_name: "{{clientgroup_name}}"
        }

we don't have to provide entity dict here...
if it's the case - main function is evaluating the "clientgroup" obj_name (line :307):

        obj_name = module.params["entity_type"]
        obj = eval(obj_name)

if we pass clientgroup - it will fail in create_object function - when retrieves the clientgroup by name (still we can pass the existing name group as a workaround).

Regards,
ND

**Comment by Vairavaprakash** [comment]
Hi ND,

commvault:
operation: "add"
entity_type: "clientgroups"
commcell: "{{ commcell }}"
args: {
clientgroup_name: "{{clientgroup_name}}"
}

use entity_type as "clientgroups"

Regards,
Vairavaprakash
