### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ghost** [CommvaultEngg/ansible#7]
from cvpysdk.commcell import Commcell
ImportError: No module named commcell

**Comment by spakhare** [comment]
Hi @srinivasjupally ,

cvpysdk is one of the requirement for commvault ansible module. Please refer below link for all the requirements.
https://github.com/Commvault/ansible#requirements

**Comment by ghost** [comment]
Not Sure what i was making wrong just followed the documentation but still receive the ansible module not found error and SDK exception

python --version
Python 3.6.9


python /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/cvpysdk-11.20-py3.6.egg/cvpysdk/cvpysdk.py
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/cvpysdk-11.20-py3.6.egg/cvpysdk/cvpysdk.py", line 76, in <module>
    from .exception import SDKException
ModuleNotFoundError: No module named '__main__.exception'; '__main__' is not a package


ansible --version
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Sep 26 2019, 13:23:47) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]


 python /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/cvpysdk-11.20-py3.6.egg/cvpysdk/commvault.py
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/cvpysdk-11.20-py3.6.egg/cvpysdk/commvault.py", line 156, in <module>
    from ansible.module_utils.basic import AnsibleModule
ModuleNotFoundError: No module named 'ansible'

Appreciate your help

**Comment by spakhare** [comment]
Hi @srinivasjupally ,

Thanks for sharing the installation and version details about ansible and python. From the details posted above, it looks like Ansible is installed on Python 2.7. And you are using python 3 to run ansible playbooks. Can you please install ansible module on python 3 and give a try?

And I also see that commvault.py is placed under "python3.6/site-packages/cvpysdk-11.20-py3.6.egg/cvpysdk/". Did by any chance we placed it there? cvpysdk is a different python package used by commvault module to perform operations. You might have to add commvault ansible module to the ansible library paths before using the playbooks.

Thanks.

**Comment by spakhare** [comment]
Please reopen if any other help is required.
