### ISSUE TITLE
Add to Ansible modules

### ISSUE THREAD

**Issue by Juergen0662** [CommvaultEngg/ansible#9]
Hi,

I am very new on Ansible, sorry for stupid question.
How do I get this module add to my Ansible to see it when I try to list he modules like ansible-doc -l.
thanks in advance
Juergen

**Comment by Vairavaprakash** [comment]
Hi Juergen,

Please refer to the below documentation for adding Commvault module to Ansible

https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html

Regards,
Vairavaprakash

**Comment by Juergen0662** [comment]
Thank you @Vairavaprakash
